// components/image-lens.vue
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
	props: {
		image: { type: Object, default: () => {} },
		sizes: { type: Array as () => string[], default: undefined },
	},

	computed: {
		imageObject() {
			return this.sizes ? this.image[this.sizes[0]] : this.image
		},
		hasAvif() {
			return this.imageObject.formats && this.imageObject.formats.avif
		},
		hasWebp() {
			return this.imageObject.formats && this.imageObject.formats.webp
		},
		ratio() {
			return (
				this.imageObject.dimensions.width /
				this.imageObject.dimensions.height
			)
		},
		imgSet() {
			if (!this.sizes) return undefined

			let set: string[] = []
			for (const size of this.sizes) {
				set.push(`${this.getPath(this.image[size].path)} ${this.image[size].dimensions.width}w`)
			}
			return set.join(',')
		},
		avifSet() {
			if (!this.sizes) return this.getPath(this.image.formats.avif)

			let set: string[] = []
			for (const size of this.sizes) {
				set.push(`${this.getPath(this.image[size].formats.avif)} ${this.image[size].dimensions.width}w`)
			}
			return set.join(',')
		},
		webpSet() {
			if (!this.sizes) return this.getPath(this.image.formats.webp)

			let set: string[] = []
			for (const size of this.sizes) {
				set.push(`${this.getPath(this.image[size].formats.webp)} ${this.image[size].dimensions.width}w`)
			}
			return set.join(',')
		},
	},

	methods: {
		/** The `static` dir isn't needed with Nuxt's routing. */
		getPath(path) {
			return path.replace(/^static/, '')
		},

		reveal(event) {
				event.target.classList.toggle('opacity-0')
				// event.target.animate({
				//         transform: ["scale(.9)", "none"],
				//         opacity: [0, 1],
				// },{
				//         duration: 700,
				//         easing: `cubic-bezier(.165,.84,.44,1)`
				// })
				// cubic-bezier(.165,.84,.44,1)
		}
	},
})
</script>

<template>
	<picture class="max-h-full" :style="{ aspectRatio: ratio }">
		<source v-if="hasAvif" :srcset="avifSet" type="image/avif" />
		<source v-if="hasWebp" :srcset="webpSet" type="image/webp" />
		<img
			class="w-full h-full max-h-full object-contain opacity-0"
			:src="getPath(imageObject.path)"
			:srcset="imgSet"
			:width="imageObject.dimensions.width"
			:height="imageObject.dimensions.height"
			loading="lazy"
			decoding="async"
			@load="reveal"
		/>
	</picture>
</template>

// www/src/lib/components/image-lens.svelte
<script>
import { onMount } from 'svelte'

/** @typedef {import('@tidaltheory/lens').ImageRecord} ImageRecord */
/** @typedef {import('@tidaltheory/lens').ImageThumbnails} ImageThumbnails */

/**
 * @param {string} path
 */
function getPath(path = '') {
	return path.replace(/^static/, '')
}

/** @type {ImageRecord | ImageThumbnails} */
export let image
/** @type {Array<string> | undefined} */
export let sizes = undefined
export let lazyLoad = true

/** @type {HTMLImageElement | null} */
let imgElement = null

/** @type {ImageRecord} */
const imageObject = sizes ? image[sizes[0]] : image
const hasAvif = Boolean(imageObject.formats?.avif)
const hasWebp = Boolean(imageObject.formats?.webp)

const imgSet = () => {
	if (!sizes) return undefined

	/** @type {Array<string>} */
	let set = []
	for (const size of sizes) {
		set.push(
			`${getPath(image[size].path)} ${image[size].dimensions.width}w`,
		)
	}

	return set.join(',')
}

const avifSet = () => {
	if (!sizes) return getPath(imageObject.formats?.avif)

	/** @type {Array<string>} */
	let set = []
	for (const size of sizes) {
		set.push(
			`${getPath(image[size].formats.avif)} ${
				image[size].dimensions.width
			}w`,
		)
	}

	return set.join(',')
}

const webpSet = () => {
	if (!sizes) return getPath(imageObject.formats?.webp)

	/** @type {Array<string>} */
	let set = []
	for (const size of sizes) {
		set.push(
			`${getPath(image[size].formats.webp)} ${
				image[size].dimensions.width
			}w`,
		)
	}

	return set.join(',')
}

/**
 * @param {HTMLImageElement} target
 */
function reveal(target) {
	// Event.target.classList.toggle('opacity-0')
	// console.log('LOADED')
	target.parentElement?.classList.remove('opacity-0')
	// Event.target.animate({
	//         transform: ["scale(.9)", "none"],
	//         opacity: [0, 1],
	// },{
	//         duration: 700,
	//         easing: `cubic-bezier(.165,.84,.44,1)`
	// })
	// cubic-bezier(.165,.84,.44,1)
}

onMount(() => {
	if (imgElement?.complete) reveal(imgElement)
})
</script>

<picture class="opacity-0 transition-opacity duration-300">
	{#if hasAvif}<source srcset={avifSet()} type="image/avif" />{/if}
	{#if hasWebp}<source srcset={webpSet()} type="image/webp" />{/if}
	<img
		bind:this={imgElement}
		use:reveal
		class="h-full w-full object-contain"
		width={imageObject.dimensions.width}
		height={imageObject.dimensions.height}
		loading={lazyLoad ? 'lazy' : undefined}
		decoding="async"
		alt=""
		sizes="100vw"
		srcset={imgSet()}
		src={getPath(imageObject.path)}
	/>
</picture>
