// components/site-nav.vue
<script>
import NavItem from '~/components/site-nav-item.vue'

export default {
	components: {
		NavItem,
	},
	data() {
		return {
			isMenuOpen: false,
		}
	},
	mounted() {
		this.$router.afterEach(() => {
			this.isMenuOpen = false
		})
	},
	methods: {
		toggleMenu() {
			this.isMenuOpen = !this.isMenuOpen
		},
	},
}
</script>

<template>
	<div class="fixed top-0 z-50 w-screen md:w-auto">
		<div
			class="relative z-10 h-16 md:h-screen px-8 py-4 md:p-6 bg-grey-900"
		>
			<div class="md:absolute flex justify-between">
				<div class="flex">
					<NuxtLink to="/">
						<div class="w-8 h-8 rounded bg-cyan-600" />
					</NuxtLink>
				</div>
				<div class="flex md:hidden">
					<button
						class="p-0 border-none rounded bg-transparent"
						@click="toggleMenu"
					>
						<div class="w-16 h-8 rounded bg-grey-600" />
					</button>
				</div>
			</div>

			<div class="flex h-full place-items-center">
				<nav class="hidden md:block">
					<div class="grid gap-8">
						<NavItem to="/work/" />
						<NavItem to="/projects/" />
						<NavItem to="/photos/" />
						<NavItem to="/about/" />
					</div>
				</nav>
			</div>
		</div>
		<div
			v-show="isMenuOpen"
			class="fixed w-screen h-screen"
			@click="toggleMenu"
		/>
		<Transition
			enter-class="transform -translate-y-full"
			enter-active-class="transition duration-200 ease-out"
			leave-active-class="transition duration-300 ease-in"
			leave-to-class="-translate-y-full"
		>
			<div
				v-if="isMenuOpen"
				class="absolute left-0 flex justify-end gap-4 w-full px-8 py-4 pb-8 bg-grey-900 bg-opacity-70 firefox:bg-opacity-90 backdrop-blur"
			>
				<div class="grid gap-8">
					<NavItem to="/work/">Work</NavItem>
					<NavItem to="/projects/">Projects</NavItem>
					<NavItem to="/photos/">Photos</NavItem>
					<NavItem to="/about/">About</NavItem>
				</div>
			</div>
		</Transition>
	</div>
</template>

// www/src/lib/components/site-nav.svelte
<script>
import { beforeNavigate } from '$app/navigation'
import { FOCUS_OUTLINE } from '$lib/classnames'
import { classes } from '$lib/transitions'

import SiteNavItem from './site-nav-item.svelte'

let isMenuOpen = false

function toggleMenu() {
	isMenuOpen = !isMenuOpen
}

beforeNavigate(async () => {
	isMenuOpen = false
})
</script>

<div class="fixed top-0 z-50 w-screen md:w-auto">
	<div class="relative z-10 h-16 bg-grey-900 px-8 py-4 md:h-screen md:p-6">
		<div
			class="flex justify-between md:absolute md:top-[calc(11vh_+_1.5rem)]"
		>
			<div class="flex">
				<SiteNavItem href="/" home label="Home" />
			</div>
			<div class="flex md:hidden">
				<button
					class="bg-transparent rounded border-none p-0 {FOCUS_OUTLINE}"
					on:click={toggleMenu}
				>
					<div class="h-8 w-16 rounded bg-grey-600" />
				</button>
			</div>
		</div>

		<div class="flex h-full place-items-center">
			<nav class="hidden md:block">
				<div class="grid gap-8">
					<SiteNavItem href="/about/" label="About" />
					<SiteNavItem href="/projects/" label="Projects" />
					<SiteNavItem href="/photos/" label="Photos" />
					<!-- <SiteNavItem href="/blog/" /> -->
				</div>
			</nav>
		</div>
	</div>
	{#if isMenuOpen}
		<div
			class="fixed h-screen w-screen"
			role="button"
			tabindex="-1"
			on:click={toggleMenu}
			on:keypress={toggleMenu}
		/>
	{/if}
	{#if isMenuOpen}
		<div
			class="absolute left-0 flex w-full justify-end gap-4 bg-grey-900 bg-opacity-70 px-8 py-4 pb-8 backdrop-blur transition"
			in:classes={{
				duration: 200,
				base: 'duration-200 ease-out',
				from: '-translate-y-full',
			}}
			out:classes={{
				duration: 150,
				base: 'duration-150 ease-in',
				to: '-translate-y-full',
			}}
		>
			<div class="grid gap-8">
				<SiteNavItem href="/about/">About</SiteNavItem>
				<SiteNavItem href="/projects/">Projects</SiteNavItem>
				<SiteNavItem href="/photos/">Photos</SiteNavItem>
				<!-- <SiteNavItem href="/blog/">Blog</SiteNavItem> -->
			</div>
		</div>
	{/if}
</div>
