// pages/photos/index.vue
<script>
import GalleryCard from '~/components/gallery-card.vue'
import PageIntro from '~/components/page-intro.vue'
import PageSection from '~/components/page-section.vue'

export default {
	components: {
		GalleryCard,
		PageIntro,
		PageSection,
	},
	async asyncData({ $content, params }) {
		let galleries = await $content('photos', params.slug)
			.only(['slug', 'title', 'cover', 'description'])
			.sortBy('createdAt', 'asc')
			.fetch()
		let { library } = await $content('imagemeta').fetch()

		galleries = galleries.map((gallery) => ({
			...gallery,
			coverImage: library[gallery.cover],
		}))

		return { galleries }
	},
}
</script>

<template>
	<article>
		<PageIntro>
			Photos
			<template #intro>
				Former side-hustle, current casual interest. Some of my
				favourite shots from past and ongoing collections.
			</template>
		</PageIntro>
		<PageSection>
			<div class="grid md:grid-cols-2 gap-4 md:gap-12 xl:gap-16">
				<GalleryCard
					v-for="gallery of galleries"
					:key="gallery.slug"
					:to="`/photos/${gallery.slug}/`"
					:cover="gallery.coverImage"
				>
					{{ gallery.title }}
				</GalleryCard>
			</div>
		</PageSection>
	</article>
</template>

// src/routes/photos/index.svelte
<script context="module">
export const load = async ({ fetch }) => {
	const posts = await fetch('/api/photos.json')
	const allPosts = await posts.json()

	return {
		props: {
			posts: allPosts,
		},
	}
}
</script>

<script>
import PageSection from '../../components/page-section.svelte'
import PageIntro from '../../components/page-intro.svelte'
import GalleryCard from '../../components/gallery-card.svelte'

export let posts
</script>

<article>
	<PageIntro>
		Photos
		<svelte:fragment slot="intro">
			Former side-hustle, current casual interest. Some of my favourite
			shots from past and ongoing collections.
		</svelte:fragment>
	</PageIntro>
	<PageSection>
		<div class="grid md:grid-cols-2 gap-4 md:gap-12 xl:gap-16">
			{#each posts as gallery}
				<GalleryCard to="{gallery.path}/" cover={gallery.coverImage}>
					{gallery.meta.title}
				</GalleryCard>
			{/each}
		</div>
	</PageSection>
</article>
