// src/routes/photos/screen-shots/index.svelte
<script context="module">
export const load = async ({ fetch }) => {
	const posts = await fetch('/api/screen-shots.json')
	const allPosts = await posts.json()

	return {
		props: {
			galleries: allPosts,
		},
	}
}
</script>

<script>
import PageIntro from '../../../components/page-intro.svelte'
import PageSection from '../../../components/page-section.svelte'
import GalleryCard from '../../../components/gallery-card.svelte'

export let galleries
</script>

<article>
	<PageIntro>Screen<br />Shots</PageIntro>
	<PageSection>
		<div class="grid md:grid-cols-2 gap-4 md:gap-12 xl:gap-16">
			{#each galleries as gallery}
				<GalleryCard to="{gallery.path}/" cover={gallery.coverImage}>
					{gallery.meta.title}
				</GalleryCard>
			{/each}
		</div>
	</PageSection>
</article>

// pages/photos/screen-shots/index.vue
<script>
import GalleryCard from '~/components/gallery-card.vue'
import PageIntro from '~/components/page-intro.vue'
import PageSection from '~/components/page-section.vue'

export default {
	components: {
		GalleryCard,
		PageIntro,
		PageSection,
	},
	async asyncData({ $content, params }) {
		let galleries = await $content('photos/screen-shots', params.slug)
			.only(['slug', 'title', 'cover', 'description'])
			.sortBy('createdAt', 'asc')
			.fetch()
		let { library } = await $content('imagemeta').fetch()

		galleries = galleries.map((gallery) => ({
			...gallery,
			coverImage: library[gallery.cover],
		}))

		return { galleries }
	},
}
</script>

<template>
	<div>
		<PageIntro> Screen<br />Shots </PageIntro>
		<PageSection>
			<div class="grid md:grid-cols-2 gap-4 md:gap-12 xl:gap-16">
				<GalleryCard
					v-for="gallery of galleries"
					:key="gallery.slug"
					:to="`/photos/screen-shots/${gallery.slug}/`"
					:cover="gallery.coverImage"
				>
					{{ gallery.title }}
				</GalleryCard>
			</div>
		</PageSection>
	</div>
</template>
