// www/src/lib/components/gallery-card.svelte
<script>
import { FOCUS_OUTLINE } from '$lib/classnames'

import Heading from './heading.svelte'
import ImageLens from './image-lens.svelte'

export let to = '/'
/** @type {import('@tidaltheory/lens').ImageRecord} */
export let cover
/** @type {string} */
export let title
/** @type {string | false} */
export let subtitle = false
/** @type {number} */
export let count

const thumbnails = cover.thumbnails ?? {}
$: fullTitle = subtitle ? [title, subtitle].join(' ') : title
</script>

<div class="group relative grid grid-rows-1 rounded-[1px] bg-grey-700">
	{#if cover}
		<div class="">
			<div
				class="absolute inset-0"
				style:background-color={cover.colors.dominant}
			/>
			<div
				class="relative grayscale transition-all duration-200 group-focus-within:grayscale-0 group-hover:grayscale-0"
			>
				<ImageLens
					image={thumbnails}
					sizes={['cover-sm', 'cover-md', 'cover-lg']}
				/>
			</div>
			<div
				class="absolute inset-0 bg-grey-800 mix-blend-lighten transition-opacity duration-200"
			/>
		</div>
	{/if}
	<div class="absolute inset-0 flex">
		<a
			class="z-10 flex-1 self-end rounded-[1px] before:absolute before:inset-0 {FOCUS_OUTLINE}"
			href={to}
		>
			<div
				class="flex items-start justify-between bg-grey-900 bg-opacity-50 p-6 backdrop-blur lg:p-10"
			>
				<Heading level={4}>
					{fullTitle}
				</Heading>
				{#if count}
					<div
						class="relative top-[0.0625rem] rounded bg-grey-700 px-2 py-[6px]"
					>
						<span class="block text-grey-200 text-lg leading-trim">
							{count}
						</span>
					</div>
				{/if}
			</div>
		</a>
	</div>
</div>

// components/gallery-card.vue
<script>
import ImageLens from './image-lens.vue'

export default {
	components: { ImageLens },
	props: {
		to: { type: String, default: '/' },
		cover: { type: Object, default: () => {} },
	},
	computed: {
		color() {
			return this.cover ? [this.cover.colors] : 'rgb(57 62 65)'
		},
	},
}
</script>

<template>
	<div class="relative grid grid-rows-1 bg-grey-700 overflow-hidden">
		<ImageLens
			v-if="cover"
			:image="cover.thumbnails"
			:sizes="['cover-sm', 'cover-md', 'cover-lg']"
			class="mix-blend-luminosity"
		/>
		<div class="absolute inset-0 flex">
			<NuxtLink
				class="peer w-full z-10 self-end before:absolute before:inset-0"
				:to="to"
			>
				<div
					class="w-full p-6 lg:p-10 bg-grey-900 bg-opacity-50 backdrop-blur firefox:bg-opacity-80"
				>
					<div
						class="font-display text-2xl lg:text-4xl font-bold leading-10 leading-trim tracking-wide uppercase"
					>
						<slot />
					</div>
				</div>
			</NuxtLink>
			<div
				class="absolute inset-0 z-0 opacity-0 peer-hover:opacity-50"
				:style="{ backgroundColor: color }"
			/>
		</div>
	</div>
</template>
