// src/lib/components/gallery-carousel.svelte
<script>
import { fade } from 'svelte/transition'

import ImageDetails from './image-details.svelte'
import ImageLens from './image-lens.svelte'

export let ref
export let images
export let onClose
</script>

<div
	bind:this={ref}
	class="fixed inset-0 z-[99] duration-200"
	transition:fade={{ duration: 150 }}
>
	<div
		class="fixed inset-0 z-[99] bg-grey-900 bg-opacity-50 backdrop-blur transition firefox:bg-opacity-80"
	/>
	<div class="zoom">
		{#each images as image, index}
			<div
				class="flex snap-center items-center justify-center p-2 md:p-4 xl:p-8"
				data-index={index}
			>
				<div class="relative">
					<ImageLens {image} />
					<div class="absolute bottom-0 left-0">
						<ImageDetails id="image-{index}"
							>Image title</ImageDetails
						>
					</div>
				</div>
			</div>
		{/each}
	</div>
	<div class="absolute top-8 right-8 z-[100] flex">
		<button
			class="bg-transparent m-0 border-0 p-0 text-white"
			type="button"
			on:click={onClose()}
		>
			<svg
				fill="none"
				viewBox="0 0 24 24"
				stroke-width="1.5"
				stroke="currentColor"
				class="h-6 w-6"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					d="M6 18L18 6M6 6l12 12"
				/>
			</svg>
		</button>
	</div>
</div>

<style>
.zoom {
	position: fixed;
	top: 0;
	left: 0;
	z-index: 100;
	display: grid;
	grid: 100% / auto-flow calc(100% - 80px);
	align-content: center;
	width: 100vw;
	height: 100vh;
	overflow: auto;
	scroll-snap-type: x mandatory;
}
</style>

// components/gallery-carousel.vue
<script lang="ts">
import Vue from 'vue'

import ImageLens from '~/components/image-lens.vue'

export default Vue.extend({
	components: {
		ImageLens,
	},

	props: {
		images: {
			type: Array,
			default: () => [],
		},
		isOpen: { type: Boolean },
		onClose: {
			type: Function,
			required: true,
		},
	},
})
</script>

<template>
	<div class="fixed inset-0 z-[99] duration-200">
		<div
			class="fixed inset-0 z-[99] bg-grey-900 bg-opacity-50 backdrop-blur firefox:bg-opacity-80 transition"
		/>
		<div :class="$style.zoom">
			<button
				v-for="(image, index) in images"
				:key="index"
				class="flex items-center justify-center p-2 md:p-4 xl:p-8 snap-center"
				type="button"
				:data-index="index"
				@click="onClose(index)"
			>
				<ImageLens :image="image" />
			</button>
		</div>
	</div>
</template>

<style lang="postcss" module>
.zoom {
	position: fixed;
	top: 0;
	left: 0;
	z-index: 100;
	display: grid;
	grid: 100% / auto-flow 100%;
	width: 100vw;
	height: 100vh;
	overflow: auto;
	scroll-snap-type: x mandatory;
}
</style>
