// src/lib/components/gallery-card.svelte
<script lang="ts">
import type { ImageRecord } from '@tidaltheory/lens'
import ImageLens from './image-lens.svelte'

export let to = '/'
export let cover: ImageRecord

const thumbnails = cover.thumbnails ?? {}
// const color = cover ? cover.colors?.[0] : 'rgb(57, 62, 65)'
</script>

<div class="group relative grid grid-rows-1 overflow-hidden bg-grey-700">
	{#if cover}
		<div class="">
			<div
				class="absolute inset-0"
				style:background-color={cover.colors.dominant}
			/>
			<div
				class="relative grayscale transition-all duration-200 group-hover:grayscale-0"
			>
				<ImageLens
					image={thumbnails}
					sizes={['cover-sm', 'cover-md', 'cover-lg']}
				/>
			</div>
			<div
				class="absolute inset-0 bg-grey-800 mix-blend-lighten transition-opacity duration-200 group-hover:opacity-0"
			/>
		</div>
	{/if}
	<div class="absolute inset-0 flex">
		<a
			class="peer z-10 w-full self-end before:absolute before:inset-0"
			href={to}
		>
			<div
				class="w-full bg-grey-900 bg-opacity-50 p-6 backdrop-blur lg:p-10"
			>
				<div
					class="font-bold uppercase tracking-wide font-display text-2xl leading-trim lg:text-4xl"
				>
					<slot />
				</div>
			</div>
		</a>
		<!-- <div
			class="absolute inset-0 z-0 opacity-0 peer-hover:opacity-50"
			style:background-color={color}
		/> -->
	</div>
</div>

// components/gallery-card.vue
<script>
import ImageLens from './image-lens.vue'

export default {
	components: { ImageLens },
	props: {
		to: { type: String, default: '/' },
		cover: { type: Object, default: () => {} },
	},
	computed: {
		color() {
			return this.cover ? [this.cover.colors] : 'rgb(57 62 65)'
		},
	},
}
</script>

<template>
	<div class="relative grid grid-rows-1 bg-grey-700 overflow-hidden">
		<ImageLens
			v-if="cover"
			:image="cover.thumbnails"
			:sizes="['cover-sm', 'cover-md', 'cover-lg']"
			class="mix-blend-luminosity"
		/>
		<div class="absolute inset-0 flex">
			<NuxtLink
				class="peer w-full z-10 self-end before:absolute before:inset-0"
				:to="to"
			>
				<div
					class="w-full p-6 lg:p-10 bg-grey-900 bg-opacity-50 backdrop-blur firefox:bg-opacity-80"
				>
					<div
						class="font-display text-2xl lg:text-4xl font-bold leading-10 leading-trim tracking-wide uppercase"
					>
						<slot />
					</div>
				</div>
			</NuxtLink>
			<div
				class="absolute inset-0 z-0 opacity-0 peer-hover:opacity-50"
				:style="{ backgroundColor: color }"
			/>
		</div>
	</div>
</template>
