// src/lib/components/image-lens.svelte
<script lang="ts">
import type { ImageRecord, ImageThumbnails } from '@tidaltheory/lens'

function getPath(path: string = '') {
	return path.replace(/^static/, '')
}

export let image: ImageRecord | ImageThumbnails
export let sizes: Array<string>

const imageObject: ImageRecord = sizes ? image[sizes[0]] : image
const hasAvif = !!imageObject.formats?.avif
const hasWebp = !!imageObject.formats?.webp
const ratio = imageObject.dimensions.width / imageObject.dimensions.height
// const placeholderColor = color

const imgSet = () => {
	if (!sizes) return undefined

	let set: string[] = []
	for (const size of sizes) {
		set.push(
			`${getPath(image[size].path)} ${image[size].dimensions.width}w`
		)
	}
	return set.join(',')
}

const avifSet = () => {
	if (!sizes) return getPath(imageObject.formats?.avif)

	let set: string[] = []
	for (const size of sizes) {
		set.push(
			`${getPath(image[size].formats.avif)} ${
				image[size].dimensions.width
			}w`
		)
	}
	return set.join(',')
}

const webpSet = () => {
	if (!sizes) return getPath(imageObject.formats?.webp)

	let set: string[] = []
	for (const size of sizes) {
		set.push(
			`${getPath(image[size].formats.webp)} ${
				image[size].dimensions.width
			}w`
		)
	}
	return set.join(',')
}

function reveal(event: Event) {
	// event.target.classList.toggle('opacity-0')
	// console.log('LOADED')
	;(event.target as HTMLElement).parentElement?.classList.toggle('opacity-0')
	// event.target.animate({
	//         transform: ["scale(.9)", "none"],
	//         opacity: [0, 1],
	// },{
	//         duration: 700,
	//         easing: `cubic-bezier(.165,.84,.44,1)`
	// })
	// cubic-bezier(.165,.84,.44,1)
}
</script>

<picture
	class="max-h-full opacity-0 transition-opacity duration-300"
	width={imageObject.dimensions.width}
	height={imageObject.dimensions.height}
	style:aspect-ratio={ratio}
>
	{#if hasAvif}<source srcset={avifSet()} type="image/avif" />{/if}
	{#if hasWebp}<source srcset={webpSet()} type="image/webp" />{/if}
	<img
		class="h-full max-h-full w-full object-contain"
		src={getPath(imageObject.path)}
		srcset={imgSet()}
		width={imageObject.dimensions.width}
		height={imageObject.dimensions.height}
		loading="lazy"
		decoding="async"
		on:load|once={reveal}
		alt=""
	/>
</picture>

// components/image-lens.vue
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
	props: {
		image: { type: Object, default: () => {} },
		sizes: { type: Array as () => string[], default: undefined },
	},

	computed: {
		imageObject() {
			return this.sizes ? this.image[this.sizes[0]] : this.image
		},
		hasAvif() {
			return this.imageObject.formats && this.imageObject.formats.avif
		},
		hasWebp() {
			return this.imageObject.formats && this.imageObject.formats.webp
		},
		ratio() {
			return (
				this.imageObject.dimensions.width /
				this.imageObject.dimensions.height
			)
		},
		imgSet() {
			if (!this.sizes) return undefined

			let set: string[] = []
			for (const size of this.sizes) {
				set.push(`${this.getPath(this.image[size].path)} ${this.image[size].dimensions.width}w`)
			}
			return set.join(',')
		},
		avifSet() {
			if (!this.sizes) return this.getPath(this.image.formats.avif)

			let set: string[] = []
			for (const size of this.sizes) {
				set.push(`${this.getPath(this.image[size].formats.avif)} ${this.image[size].dimensions.width}w`)
			}
			return set.join(',')
		},
		webpSet() {
			if (!this.sizes) return this.getPath(this.image.formats.webp)

			let set: string[] = []
			for (const size of this.sizes) {
				set.push(`${this.getPath(this.image[size].formats.webp)} ${this.image[size].dimensions.width}w`)
			}
			return set.join(',')
		},
	},

	methods: {
		/** The `static` dir isn't needed with Nuxt's routing. */
		getPath(path) {
			return path.replace(/^static/, '')
		},

		reveal(event: Event) {
				// event.target.classList.toggle('opacity-0')
				;(event.target as HTMLElement).parentElement?.classList.toggle('opacity-0')
				// event.target.animate({
				//         transform: ["scale(.9)", "none"],
				//         opacity: [0, 1],
				// },{
				//         duration: 700,
				//         easing: `cubic-bezier(.165,.84,.44,1)`
				// })
				// cubic-bezier(.165,.84,.44,1)
		}
	},
})
</script>

<template>
	<picture
		class="max-h-full transition-opacity duration-300 opacity-0"
		:width="imageObject.dimensions.width"
		:height="imageObject.dimensions.height"
		:style="{ aspectRatio: ratio, backgroundColor: [imageObject.colors] }"
	>
		<source v-if="hasAvif" :srcset="avifSet" type="image/avif" />
		<source v-if="hasWebp" :srcset="webpSet" type="image/webp" />
		<img
			class="w-full h-full max-h-full object-contain"
			:src="getPath(imageObject.path)"
			:srcset="imgSet"
			:width="imageObject.dimensions.width"
			:height="imageObject.dimensions.height"
			loading="lazy"
			decoding="async"
			@load.once="reveal"
		/>
	</picture>
</template>
