// www/src/lib/components/mention-link.svelte
<script>
import { FOCUS_OUTLINE } from '$lib/classnames'

import LogoClari from './logo-clari.svelte'
import LogoLift from './logo-lift.svelte'
import LogoShowbie from './logo-showbie.svelte'

const SITES = {
	lift: {
		href: 'https://liftinteractive.com',
		logo: LogoLift,
	},
	showbie: {
		href: 'https://www.showbie.com',
		logo: LogoShowbie,
	},
	clari: {
		href: 'https://www.clari.com',
		logo: LogoClari,
	},
	instagram: {
		href: 'https://www.instagram.com/stormwarning/',
		logo: undefined,
	},
	flickr: {
		href: 'https://www.flickr.com/photos/rustyangel/',
		logo: undefined,
	},
}

/** @type {keyof typeof SITES} */
export let site

const { href, logo } = SITES[site]
</script>

<a
	class="inline-flex items-baseline gap-1 rounded bg-grey-700 px-1 align-baseline text-white no-underline hover:bg-grey-600 {FOCUS_OUTLINE}"
	{href}
	target="_blank"
	rel="noopener noreferrer"
>
	<svelte:component this={logo} />
	<span class="font-semibold tracking-tight">
		<slot />
	</span>
</a>

// components/mention-link.vue
<script lang="ts">
import Vue from 'vue'

import LogoClari from '~/components/logo-clari.vue'
import LogoLift from '~/components/logo-lift.vue'
import LogoShowbie from '~/components/logo-showbie.vue'

const sites = {
	lift: {
		href: 'https://liftinteractive.com',
		logo: LogoLift,
	},
	showbie: {
		href: 'https://www.showbie.com',
		logo: LogoShowbie,
	},
	clari: {
		href: 'https://www.clari.com',
		logo: LogoClari,
	},
}

export default Vue.extend({
	props: {
		site: {
			type: String,
			required: true,
		},
	},

	computed: {
		href() {
			return sites[this.site].href
		},
		logo() {
			return sites[this.site].logo
		},
	},
})
</script>

<template>
	<a
		class="inline-flex items-baseline gap-1 px-1 bg-grey-700 hover:bg-grey-600 text-white rounded align-baseline"
		:href="href"
	>
		<component :is="logo" class="w-[1em] h-[1em] self-center" />
		<span class="font-semibold tracking-tight">
			<slot />
		</span>
	</a>
</template>
