// www/src/lib/components/page-intro.svelte
<script>
import ObserveIntersection from 'svelte-intersection-observer'

import Heading from './heading.svelte'
import PageSection from './page-section.svelte'
import SubHeading from './sub-heading.svelte'

/** @type {string | false} */
export let subtitle = false

/** @type {HTMLDivElement} */
let header
</script>

<PageSection>
	<ObserveIntersection once element={header} let:intersecting>
		<div
			class="grid grid-cols-4 xl:grid-cols-2 xl:gap-16"
			bind:this={header}
		>
			<div
				class="col-span-full grid gap-4 md:col-span-3 md:gap-6 md:pt-8 xl:gap-8 xl:pt-12"
				class:opacity-0={!intersecting}
				style:transform="translateZ(0)"
			>
				<Heading shouldShow={intersecting} transitionIn>
					<slot />
				</Heading>
				{#if subtitle}
					<SubHeading level="3" shouldShow={intersecting}>
						{subtitle}
					</SubHeading>
				{/if}
			</div>
			{#if $$slots.intro}
				<div
					class="col-span-3 col-start-2 row-start-2 pt-[9vh] md:pt-[11vh] xl:pt-36"
				>
					<slot name="intro" {intersecting} />
				</div>
			{/if}
		</div>
	</ObserveIntersection>
</PageSection>

// components/page-intro.vue
<script>
import Heading from '~/components/Heading.vue'
import PageSection from '~/components/page-section.vue'
import Text from '~/components/Text.vue'
export default {
    components: { Heading, PageSection, TextContent: Text },
}
</script>

<template>
    <PageSection>
        <div class="grid grid-cols-4 xl:grid-cols-2 xl:gap-16">
            <div class="col-span-full md:col-span-3 md:pt-8 xl:pt-12">
                <Heading><slot /></Heading>
            </div>
            <div
                v-if="!!$slots.intro"
                class="
                    col-span-3
                    md:col-start-2
                    row-start-2
                    pt-[9vh]
                    md:pt-[11vh]
                    xl:pt-36
                "
            >
                <TextContent element="p">
                    <slot name="intro" />
                </TextContent>
            </div>
        </div>
    </PageSection>
</template>
