// src/routes/photos/+page.svelte
<script>
import GalleryCard from '$lib/components/gallery-card.svelte'
import PageIntro from '$lib/components/page-intro.svelte'
import PageSection from '$lib/components/page-section.svelte'

// Suggestion (check code before using, and possibly convert to data.X access later):
/** @type {import('./$types').PageData} */
export let data
$: posts = data.json
</script>

<svelte:head>
	<title>Photos — Tidal Theory</title>
</svelte:head>

<article>
	<PageIntro>
		Photos
		<svelte:fragment slot="intro">
			Former side-hustle, current casual interest. Some of my favourite
			shots from past and ongoing collections.
		</svelte:fragment>
	</PageIntro>
	<PageSection>
		<div class="grid gap-4 md:grid-cols-2 md:gap-12 xl:gap-16">
			{#each posts as gallery}
				<GalleryCard
					to="{gallery.path}/"
					cover={gallery.coverImage}
					title={gallery.meta.title}
				/>
			{/each}
		</div>
	</PageSection>
</article>

// pages/photos/index.vue
<script>
import GalleryCard from '~/components/gallery-card.vue'
import PageIntro from '~/components/page-intro.vue'
import PageSection from '~/components/page-section.vue'

export default {
	components: {
		GalleryCard,
		PageIntro,
		PageSection,
	},
	async asyncData({ $content, params }) {
		let galleries = await $content('photos', params.slug)
			.only(['slug', 'title', 'cover', 'description'])
			.sortBy('createdAt', 'asc')
			.fetch()
		let { library } = await $content('imagemeta').fetch()

		galleries = galleries.map((gallery) => ({
			...gallery,
			coverImage: library[gallery.cover],
		}))

		return { galleries }
	},
}
</script>

<template>
	<article>
		<PageIntro>
			Photos
			<template #intro>
				Former side-hustle, current casual interest. Some of my
				favourite shots from past and ongoing collections.
			</template>
		</PageIntro>
		<PageSection>
			<div class="grid md:grid-cols-2 gap-4 md:gap-12 xl:gap-16">
				<GalleryCard
					v-for="gallery of galleries"
					:key="gallery.slug"
					:to="`/photos/${gallery.slug}/`"
					:cover="gallery.coverImage"
				>
					{{ gallery.title }}
				</GalleryCard>
			</div>
		</PageSection>
	</article>
</template>
